### ISSUE TITLE
ConnectionError: HTTPConnectionPool Error

### ISSUE THREAD

**Issue by emre570** [cobanov/easy-web-summarizer#4]
@cobanov Abi projeyi Docker'da veya Streamlit Cloud'da çalıştırınca şu hatayı alıyorum ancak localde .py dosyasını çalıştırınca çalışıyor.

`requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=11434): Max retries exceeded with url: /api/chat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f47d107be80>: Failed to establish a new connection: [Errno 111] Connection refused'))`

Ollama'nın (eğer web üzerinde veya başka bir uzak platformda servis edilecekse) başka bir server üzerinde çalışması gerekiyormuş. Neler yapıılabilir?

**Comment by cobanov** [comment]
localde calismasinin nedeni 127.0.0.1 ile calistirdigin icin, agdaki diger cihazlardan dinlenmesi icin 0.0.0.0 adresinden yayinlanmasi gerekiyor. docker icin --network=host parametresini koymayi unutma
